[General]
include = shadowrocket.conf
update-url = https://raw.githubusercontent.com/z7-btc/shadowrocket-custom-module/main/custom-apps-extension.conf

[Proxy Group]
CHATGPT = url-test,policy-regex-filter=台湾|Taiwan|🇹🇼|日本|Japan|🇯🇵|新加坡|Singapore|🇸🇬|韩国|Korea|South Korea|🇰🇷|美国|USA|United States|🇺🇸|英国|United Kingdom|🇬🇧|加拿大|Canada|🇨🇦|澳大利亚|澳洲|Australia|🇦🇺|德国|Germany|🇩🇪|法国|France|🇫🇷|荷兰|Netherlands|🇳🇱,interval=600,timeout=5,tolerance=50,url=https://cp.cloudflare.com/generate_204
MEXC = url-test,policy-regex-filter=台湾|Taiwan|🇹🇼|澳大利亚|澳洲|Australia|🇦🇺|新西兰|New Zealand|🇳🇿|泰国|Thailand|🇹🇭|越南|Vietnam|🇻🇳,interval=600,timeout=5,tolerance=50,url=https://cp.cloudflare.com/generate_204
TALKTONE = url-test,policy-regex-filter=(?i)(?=.*(?:美国|USA|United States|🇺🇸|加拿大|Canada|🇨🇦|英国|UK|United Kingdom|🇬🇧))(?=.*(?:家宽|住宅|Residential)).*,interval=600,timeout=5,tolerance=50,url=https://cp.cloudflare.com/generate_204

[Rule]
DOMAIN-SET,https://raw.githubusercontent.com/z7-btc/shadowrocket-custom-module/main/rules/chatgpt.list,CHATGPT
DOMAIN-SET,https://raw.githubusercontent.com/z7-btc/shadowrocket-custom-module/main/rules/mexc.list,MEXC
DOMAIN-SET,https://raw.githubusercontent.com/z7-btc/shadowrocket-custom-module/main/rules/talkatone.list,TALKTONE
