[General]
include = shadowrocket.conf
update-url = https://raw.githubusercontent.com/z7-btc/shadowrocket-custom-module/main/custom-apps-extension.conf

[Proxy Group]
CHATGPT = url-test,policy-regex-filter=(?i)(日本|东京|東京|大阪|Japan|Tokyo|Osaka|🇯🇵|\bJP\b),interval=600,timeout=5,tolerance=50,url=https://cp.cloudflare.com/generate_204
MEXC = url-test,policy-regex-filter=(?i)(香港|Hong Kong|Hongkong|🇭🇰|\bHK\b),interval=600,timeout=5,tolerance=50,url=https://cp.cloudflare.com/generate_204
TALKTONE = url-test,policy-regex-filter=(?i)(Talkatone|Talktone|(?=.*(美国|United States|USA|🇺🇸|\bUS\b))(?=.*(家宽|住宅|Residential|ISP|原生)).*),interval=600,timeout=5,tolerance=50,url=https://cp.cloudflare.com/generate_204
